export default Object.freeze({
  ASICS: {_id: 0, name: 'ASICS'},
  CONVERSE: {_id: 1, name: 'CONVERSE'},
  JORDAN: {_id: 2, name: 'JORDAN'},
  NEW_BALANCE: {_id: 3, name: 'NEW BALANCE'},
  NIKE: {_id: 4, name: 'NIKE'},
  PUMA: {_id: 5, name: 'PUMA'},
  REEBOK: {_id: 6, name: 'REEBOK'},
  SAUCONY: {_id: 7, name: 'SAUCONY'},
  UNDER_ARMOUR: {_id: 8, name: 'UNDER ARMOUR'},
  VANS: {_id: 9, name: 'VANS'},
  YEEZY: {_id: 10, name: 'YEEZY'},
  ADIDAS: {_id: 11, name: 'ADIDAS'},
  OTHER: {_id: 12, name: 'OTHER'},
});
